# This is a basic workflow to help you get started with Actions
name: Create-artfact
on:
  push:
    branches: [ master ]
  
jobs:
    artifact-download-available:
      runs-on: ubuntu-latest
      steps: 
        - name: Step 1 Create a temporary artifact download folder
          run: mkdir downloads
          
        - name: Step 2 Add artifact to publish to the temp folder
          run: |
            cd downloads
            echo 'alpha' > alpha.html
            echo 'bravo' > bravo.html
            echo 'charlie' > charlie.html
            cd ..
        
        - name: Steps 3 - Add the artifacts to publish to the temp folder
          run: | 
            uses: actions/upload-artifacts@v2
            with: 
              name: assests-for-download
              path: downloads
