name: CI
on: 
   push:
    branches: [master]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository in our runner
        uses: actions/checkout@v2

      - name: install Dependencies
        run: |
          echo "Running Installing Dependencies"
          npm install

      - name: Run linting
        run:  |
          echo "Running Linting Test..."
          npm run lint
        env:
           CI: true
      


