name: Website_CI
on: 
  push:
    branches:
      [master]
   # - 'SLIIK**'
  
  pull_request:
    types: [opened, synchronize]

jobs:
  code_checks:
    name: checking Syntax
    runs-on: ubuntu-latest
    steps:
      - name: checks
        run:
          echo "Welcome to yaml"
