name: Website_CI
on: 
  push:
    branches:
      [master]
   # - 'SLIIK**'
  
  pull_request:
    types: [opened, synchronize]

jobs:
  code_checks:
    name: checking Syntax
    runs-on: ubuntu-latest
    steps:
      - name: checks
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2